title: Tank-Mates Aquaponics
logo: /assets/img/logo.png
description: A blog about fishkeeping
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
author: tmaquaponics


plugins:
 - jekyll-feed
