title: Tank-Mates Aquaponics
logo: https://avatars.githubusercontent.com/u/182496440?v=4
description: A blog about fishkeeping
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
author: tmaquaponics
excerpt_separator: <!--more-->
collections:
  - products
  - posts
collections_dir: db

plugins:
 - jekyll-feed
